### ISSUE TITLE
Removing event listener from the form

### ISSUE THREAD

**Issue by valicm** [SecureTrading/js-payments#1132]
Hi, 

Have a question/problem with event listener added in branch STJS-649
which ought to fix the wrong form id.

But on specific implementations, in my case Drupal Commerce, all payment methods are radio buttons which can be switched with ajax call, so that each payment method loads their integration.

Problem with SC and this change is, that after switching from SC payment method on checkout implementation on entire form still is active event listener added  in STJS-649 (CardFrames._preventFormSubmit)

Which blocks submit of the entire form even different method is chosen. Prior that change it has been worked properly. I haven't found a way to de-attach SC event listener.

Not sure if there is anything on my side except removing the entire form from the DOM and then reattach maybe?

You can check current implementation here https://git.drupalcode.org/project/commerce_securetrading/-/blob/8.x-1.x/js/commerce_securetrading.form.js
https://www.dropbox.com/s/szaan42q2u4o6g8/st_js.png?dl=0

**Comment by pgs-gmartowski** [comment]
Hi @valicm ,

Thank you for raising this, we had to add `CardFrames._preventFormSubmit` method to prevent submitting form prematurely.
We are currently working on fix which allows user to remove 'prevent form submit' listener; it should be available in version 2.4.0.

**Comment by wirus15** [comment]
Hi @valicm 
We've already released the fix for that in the `2.3.1` version. 

We added the unbinding to the `ST.destroy()` function. It's a function meant to be called when the payment form is no longer needed. Once called, the listener blocking the default behavior of the form is being removed, and the form could be submitted. 

There are 2 ways of calling that method: 
1. You can just call the method on the `ST` instance.
2. It is called automatically when the control frame iframe disappears from the DOM tree.

It all depends on what exactly happens when switching the radio buttons.

1. If the ST form is being removed from the DOM (the iframes) then there should be no additional actions required because the `destroy()` function is called automatically and the listener is being unbound.
2. It becomes a little more complicated if the payment form (iframes), once instantiated, is being only hidden instead of removing them from the DOM tree completely. Then you have to either remove them or call the `destroy()` function manually. The first option is recommended in case you want to use the ST payments again. Once destroyed, you have to call the `ST()` function again to make use of it. Not removing the form from the DOM results in duplicated input fields.

I hope this resolves your issue 😉 Should you have any further questions, you can write here or contact our support team directly.

Cheers 😉

**Comment by valicm** [comment]
Hi, 

Tnx. Remove iframe after switching payment method on radio buttons solves the problem.

https://git.drupalcode.org/project/commerce_securetrading/-/commit/c1ee6658243532127d7e7527d239599e2604b567

We can mark it as solved
